### PR TITLE
add cache substituter

### PR DESCRIPTION
**Pull request by edrex**

### CODE REVIEW

**Comment by srid** [comment]
When running `nix develop` with these lines, I saw:

image

It was only building Emanote on macOS, but that's probably because I use a custom ema as input. Haven't tested it on emanote-template yet ...

**Comment by edrex** [comment]
I'm not sure if `nixConfig` from dependency (input, non-root) flakes apply, but it seems like they should. In that case these lines could be included in emanote, or ema.

The lines don't apply when used with `nix run` (https://github.com/NixOS/nix/issues/6170).

Also you can only add substitutors when running in a privileged context, which means:

 - single user mode
 - you are in `trusted-users`
 - i guess portable nix etc

**Comment by edrex** [comment]
> I'm not sure if nixConfig from dependency (input, non-root) flakes apply

They don't (https://github.com/NixOS/nix/pull/4189#issuecomment-717067395)

> Currently it only uses options from the top-level flake. Since dependencies are fetched lazily that's really the only option, unless we propagate options into the lock file.

, so adding the cache to emanote-template is desirable.

**Comment by srid** [comment]
I haven't tested this, but maybe in a different PR we should update README with what works for cache and what doesn't. `nix run` and `nix build` are the main workflows for this repo.

**Comment by edrex** [comment]
> maybe running nix build first would prime the store?

It seems to - `nix run` loads quickly after `nix build` with cache.

**Pull request merged**
